version: "3.5"
services:
    toastmanager:
        image: hermanntoast/toastmanager-webui:latest
        container_name: toastmanager_webui
        ports:
            - "8000:8000"
        links:
            - toastmanager_database:mysql
        depends_on:
            - toastmanager_database
        environment:
            - ROOT_PASSWORD=Muster!
            - DEV_MODE=0
            - SERVER_NAME=manager.hermann-toast.de
            - TIMEZONE=Europe/Berlin
            - SERVER_COLOR=green
            - SERVER_PORT=8000
            - MYSQL_HOST=toastmanager_database
            - MYSQL_USER=root
            - MYSQL_PASSWORD=Muster!
            - MYSQL_DATABASE=toastmanager
        volumes:
            - "./app:/opt/app/"

    toastmanager_database:
        image: mariadb:latest
        container_name: toastmanager_database
        environment:
            - MYSQL_ROOT_PASSWORD=Muster!
            - MYSQL_DATABASE=toastmanager
        volumes:
            - ./data/database:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - toastmanager_database:mysql
        depends_on:
          - toastmanager_database
        ports:
          - '8080:80'
        environment:
          PMA_HOST: toastmanager_database
          MYSQL_ROOT_PASSWORD: Muster!
